//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodbook.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookComment
    {
        public long CommentId { get; set; }
        public long CommentedCookId { get; set; }
        public long CommentOwnerId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime DateInserted { get; set; }
        public int Rating { get; set; }
    
        public virtual Cook Cook { get; set; }
        public virtual Cook Cook1 { get; set; }
    }
}
