//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodbook.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.RecipeComments = new HashSet<RecipeComment>();
            this.RecipeImages = new HashSet<RecipeImage>();
            this.Cooks = new HashSet<Cook>();
        }
    
        public long RecipeId { get; set; }
        public long CookId { get; set; }
        public string Name { get; set; }
        public long CuisineId { get; set; }
        public long FoodCategoryId { get; set; }
        public string RecipeText { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<long> CaloricityId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public bool IsEnabled { get; set; }
        public int PreparationTime { get; set; }
        public string Ingredients { get; set; }
        public long ComplexityId { get; set; }
    
        public virtual Caloricity Caloricity { get; set; }
        public virtual Complexity Complexity { get; set; }
        public virtual Cook Cook { get; set; }
        public virtual Cuisine Cuisine { get; set; }
        public virtual FoodCategory FoodCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeComment> RecipeComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeImage> RecipeImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cook> Cooks { get; set; }
    }
}
